### ISSUE TITLE
Feed headings and content swapped

### ISSUE THREAD

**Issue by mordae** [thecontextnet/public#1]
I have added the XML news feed to Flym and headings and content appear swapped.

**Comment by mordae** [comment]
OK, I take that back. Is it normal that some articles have shorter body than heading?

**Comment by f055** [comment]
Hi. Thanks for reporting this. Yes, most of the times body and heading have similar length, but sometimes the heading is quite longer than the body. In general, the heading is the main piece, the body is intended for context, and the full article is always available at the source. However, I noticed I don't include the source url in the feed, I will fix that.

**Comment by mordae** [comment]
Thanks for the comment.
