### ISSUE TITLE
Apostrophes render incorrectly in the XML feed

### ISSUE THREAD

**Issue by mordae** [thecontextnet/public#2]
Apostrophes render as carons over the following letter when viewing through an RSS reader (Flym).

**Comment by f055** [comment]
Can you link to a particular example?

**Comment by mordae** [comment]
You convert them to `#xE2;&#x80;&#x99;` for some reason. Check current feed and look for the article about Corbyn.

**Comment by f055** [comment]
Good catch, thanks. I'll look into it.

**Comment by f055** [comment]
The [XML::RSS](http://search.cpan.org/~shlomif/XML-RSS-1.59/lib/XML/RSS.pm) module has a weird encoding method for some utf8 characters, like the fancy apostrophes. From now on the feed will swap them for regular ones, like `'`.
